apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: fix-limit-runners
spec:
  rules:
    - name: fix-limit-runners
      preconditions:
        any:
          - key: "{{ request.object.spec.containers[*].resources.limits.cpu }}"
            operator: GreaterThan
            value: 1
          - key: "{{ request.object.spec.containers[*].resources.limits.memory }}"
            operator: GreaterThan
            value: 1Gi
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - name: "*"
                resources:
                  limits:
                    cpu: 1
                    memory: 1Gi
