# Deploying Web app and Runner
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsplayground-webapp-deployment
  labels:
    app: nginx
spec:
  template:
    metadata:
      labels:
        app: jsplayground
        component: webapp
    spec:
      containers:
        - name: webapp
          image: jsplayground/web:latest
          ports:
            - containerPort: 8080
          env:
            - name: RUNNER_URL
              value: http://jsplayground-runner-service
