apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsplayground-webapp-deployment
spec:
  replicas: 1 # You can adjust the number of replicas
  selector:
    matchLabels:
      app: jsplayground
      component: webapp
  template:
    metadata:
      labels:
        app: jsplayground
        component: webapp
    spec:
      containers:
        - name: webapp
          image: maxtho/jsplayground:web
          ports:
            - containerPort: 8080
          env:
            - name: RUNNER_URL
              value: http://jsplayground-runner-service
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
