# Deploying Web app and Runner
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsplayground-runner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jsplayground
      component: runner
  template:
    metadata:
      labels:
        app: jsplayground
        component: runner
    spec:
      containers:
        - name: runner
          image: maxtho/jsplayground:runner
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jsplayground-runner-service
spec:
  selector:
    app: jsplayground
    component: runner
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
